import turtle

main_turtle = turtle.Turtle()
def bogdans_pyatiugolnik(x,y):
    main_turtle.color('green')
    main_turtle.penup()
    main_turtle.goto(x,y)
    main_turtle.pendown()
    main_turtle.begin_fill()
    main_turtle.forward(50)
    main_turtle.right(45)
    main_turtle.forward(33)
    main_turtle.right(90)
    main_turtle.forward(33)
    main_turtle.right(45)
    main_turtle.forward(50)
    main_turtle.right(90)
    main_turtle.forward(50) 
    main_turtle.end_fill()   
bogdans_pyatiugolnik(0,0)
main_turtle.hideturtle()
turtle.exitonclick()